server:
  port: ${SERVER_PORT:10010}
spring:
  application:
    name: user
  cloud:
    consul:
      host: 47.95.121.41
      discovery:
        prefer-ip-address: true
        healthCheckInterval: 15s
  data:
    mongodb:
      uri: mongodb://47.95.121.41:27017/footprint
debug: true