server:
  port: ${SERVER_PORT:20000}
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: 47.95.121.41
      port: 8500
      discovery:
        prefer-ip-address: true
        healthCheckPath: ${management.contextPath}/health
        healthCheckInterval: 3s
        service-name: gateway