server:
  port: ${SERVER_PORT:20000}
spring:
  application:
    name: gateway
  cloud:
    consul:
      #host: localhost
      host: 192.168.0.105
      discovery:
        prefer-ip-address: true
        healthCheckInterval: 15s
        instance-id: gateway
  data:
    mongodb:
      uri: mongodb://47.95.121.41:27017/footprint
zuul:
  routes:
    user:
      path: /api/user/**
      serviceId: user
      stripPrefix: false
    comment:
      path: /api/comment/**
      serviceId: comment
      stripPrefix: false
    common:
       path: /api/common/**
       serviceId: common
       stripPrefix: false
footprint:
  filter:
    no_token_verification:
      - /api/user/sign-in
      - /api/user/sign-up
      - /api/common/auth-code
      - /api/common/auth-code/verify
      - /api/comment/article/detail
      - /api/comment/article
debug: true


