server:
  port: ${SERVER_PORT:20000}
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      discovery:
        prefer-ip-address: true
        healthCheckInterval: 15s
        service-name: gateway
debug: true




